/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/-/cron": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/-/cron/{task_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/-/api/cron/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Tasks */
                            tasks: components["schemas"]["TaskResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/-/api/cron/tasks/{task_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Name */
                            name: string;
                            /** Handler */
                            handler: string;
                            /** Config */
                            config: {
                                [key: string]: unknown;
                            };
                            /** Schedule Type */
                            schedule_type: string;
                            /** Schedule Config */
                            schedule_config: string;
                            /** Schedule Description */
                            schedule_description: string;
                            /** Timezone */
                            timezone: string | null;
                            /** Overlap Policy */
                            overlap_policy: string;
                            /** Retry Max */
                            retry_max: number;
                            /** Retry Backoff */
                            retry_backoff: string;
                            /** Enabled */
                            enabled: boolean;
                            /** Next Run At */
                            next_run_at: string | null;
                            /** Last Run At */
                            last_run_at: string | null;
                            /** Last Status */
                            last_status: string | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/-/api/cron/tasks/{task_name}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Runs */
                            runs: components["schemas"]["RunResponse"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/-/api/cron/tasks/{task_name}/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_name: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, never>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Ok */
                            ok: boolean;
                            /** Message */
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/-/api/cron/tasks/{task_name}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    task_name: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Enabled */
                        enabled: boolean;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Ok */
                            ok: boolean;
                            /** Enabled */
                            enabled: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** TaskResponse */
        TaskResponse: {
            /** Name */
            name: string;
            /** Handler */
            handler: string;
            /** Config */
            config: {
                [key: string]: unknown;
            };
            /** Schedule Type */
            schedule_type: string;
            /** Schedule Config */
            schedule_config: string;
            /** Schedule Description */
            schedule_description: string;
            /** Timezone */
            timezone: string | null;
            /** Overlap Policy */
            overlap_policy: string;
            /** Retry Max */
            retry_max: number;
            /** Retry Backoff */
            retry_backoff: string;
            /** Enabled */
            enabled: boolean;
            /** Next Run At */
            next_run_at: string | null;
            /** Last Run At */
            last_run_at: string | null;
            /** Last Status */
            last_status: string | null;
        };
        /** RunResponse */
        RunResponse: {
            /** Id */
            id: number;
            /** Task Name */
            task_name: string;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Status */
            status: string;
            /** Error Message */
            error_message: string | null;
            /** Attempt */
            attempt: number;
            /** Duration Ms */
            duration_ms: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
