/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Handler = string;
export type ScheduleType = string;
export type ScheduleDescription = string;
export type Timezone = string | null;
export type Enabled = boolean;
export type NextRunAt = string | null;
export type LastRunAt = string | null;
export type LastStatus = string | null;
export type Tasks = TaskSummary[];
export type Handlers = string[];

export interface IndexPageData {
  tasks: Tasks;
  handlers: Handlers;
  [k: string]: unknown;
}
export interface TaskSummary {
  name: Name;
  handler: Handler;
  schedule_type: ScheduleType;
  schedule_description: ScheduleDescription;
  timezone: Timezone;
  enabled: Enabled;
  next_run_at: NextRunAt;
  last_run_at: LastRunAt;
  last_status: LastStatus;
  [k: string]: unknown;
}
